### ISSUE TITLE
Error when running npm run build

### ISSUE THREAD

**Issue by TjalleWired** [xeolabs/xeoengine#330]
**Describe the bug**
Error when trying to build the project using `npm run build`

Log of when error appears;
[2020-05-28T09_48_42_493Z-debug.log](https://github.com/xeolabs/xeogl/files/4694707/2020-05-28T09_48_42_493Z-debug.log)

**To Reproduce**
_Run everything with elevated user perms._

use git to clone latest repo
run `npm install` ,which yields the expected results.
`npm run build` give out an error.

```
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/mnt/c/Users/admin/Desktop/xeogl/xeogl/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/mnt/c/Users/admin/Desktop/xeogl/xeogl/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/mnt/c/Users/admin/Desktop/xeogl/xeogl/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xeogl@0.9.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xeogl@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Expected behavior**
A succesfull build using npm run

**Desktop (please complete the following information):**
 - OS: Windows 10 Latest stable release, NPM v6.14.4, Node v12.16.3
 

**Additional context**
Also have tried using WSL Ubuntu and Ubuntu 18.04 LTS

**Comment by TjalleWired** [comment]
It seems that the error is in a gulp version mismatch. Not entirely sure yet.

Also have tried downgrading to current LTS node version (12.17)

**Comment by moriarty233** [comment]
I miss a same problem.
Have you solve it yet?

**Comment by TjalleWired** [comment]
> I miss a same problem.
> Have you solve it yet?

Not yet. I will post my fix, IF I ever find it .
I suggest you do the same ;)

Problem seems to be in the versions of the packages.

**Comment by moriarty233** [comment]
I find a solution.
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
